🏗️ Pull Request Reviews
calibreapp/cli pull request #576
Opened 2023-07-06 08:10 UTC by benschwarz

In this PR:

- [ ] Add Pull Request Review commands
- [ ] Update changelog

2023-07-12 03:53 UTC, benschwarz commented on src/api/pull-request-review.js
> +  query ListPages(
```suggestion
  query ListPullRequestReviews(
```

2023-08-15 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calibreapp/cli?pullRequest=576) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calibreapp/cli?pullRequest=576) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calibreapp/cli?pullRequest=576) it.</sub>

2023-09-01 01:05 UTC, robmorieson approved these changes
Not super familiar with the CLI repo (a bit more after reviewing this!) but had a good look through all the same and couldn't spot anything that looks amiss

2023-09-01 05:51 UTC, thefoxis requested changes

2023-09-01 05:51 UTC, thefoxis commented on src/cli/test/create.js
> +    describe: 'Test result JSON will be POSTed to this URL.'
I think I know what this means,  but still, I wouldn't abbreviate the explanation. How about `Test result JSON will be sent to this URL via the HTTP POST method.`?

2023-09-01 05:51 UTC, thefoxis commented on src/cli/site/pull-request-reviews.js
> +const describe = 'List Pull Request reviews for a selected Site.'
```suggestion
const describe = 'List Pull Request Reviews for a selected Site.'
```

2023-09-01 05:51 UTC, thefoxis commented on src/cli/site/create-pull-request-review.js
> +    describe: 'Wait for PR to be evaluated before returning.',
```suggestion
    describe: 'Wait for pull request to be evaluated before returning.',
```

2023-09-01 05:51 UTC, thefoxis commented on src/cli/site/create-pull-request-review.js
> +      'The branch of the preview deployment. e.g. "my-pull-request-123".',
```suggestion
      'The branch of the preview deployment. e.g.: "my-pull-request-123".',
```

2023-09-01 05:51 UTC, thefoxis commented on src/cli/site/create-pull-request-review.js
> +      'The base URL of the preview deployment (e.g. https://my-pull-request-123.example.com).',
```suggestion
      'The base URL of the preview deployment (e.g.: https://my-pull-request-123.example.com).',
```

2023-09-01 05:51 UTC, thefoxis commented on CHANGELOG.md
> +- Adds new command: `calibre site pull-request-reviews` to list Pull Request reviews.
```suggestion
- Adds new command: `calibre site pull-request-reviews` to list Pull Request Reviews.
```

2023-09-01 05:51 UTC, thefoxis commented on CHANGELOG.md
> +- Adds new command: `calibre site pull-request-review` to retrieve / display an existing Pull Request review.
```suggestion
- Adds new command: `calibre site pull-request-review` to retrieve and display an existing Pull Request Review.
```

2023-09-01 05:51 UTC, thefoxis commented on CHANGELOG.md
> +- Adds new command: `calibre site pull-request-review` to retrieve / display an existing Pull Request review.
you might want to consider linking Pull Request Review to docs at least once since it's mentioned quite a bit here

2023-09-01 08:35 UTC, benschwarz commented on src/cli/test/create.js
> +    describe: 'Test result JSON will be POSTed to this URL.'
```suggestion
    describe: 'Test result JSON will be sent to this URL using HTTP POST.'
```

2023-09-05 08:21 UTC, merged